# Generated by Django 4.1.10 on 2023-08-04 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_comment_comment_blog_commen_created_0e6ed4_idx'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='is_active',
            new_name='active',
        ),
    ]
